version: '3.8'

services:
  dashboard-service:
    container_name: flask
    build:
      dockerfile: Dockerfile
      context: ./kisa-dashboard-service
    restart: always
    network_mode: host
    depends_on:
      - mongo-db
    environment:
      MONGO_URI_DB1: "mongodb://localhost:27017/prediction_service"
      MONGO_URI_DB2: "mongodb://localhost:27017/gcs_drone"

  gcs-service:
    container_name: dotnet
    build:
      dockerfile: Dockerfile
      context: ./kisa-gcs-service
    restart: always
    network_mode: host
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: mongodb
    restart: always
    network_mode: host
    volumes:
      - mongodb_data:/data/db

  web-app:
    container_name: react
    build:
      dockerfile: Dockerfile
      context: ./kisa-webapp
    restart: always
    network_mode: host
    depends_on:
      - dashboard-service
      - gcs-service

volumes:
  mongodb_data: