version: '3.10'

services:
#  ardupilot:
#    container_name: arducopter
#    build:
#      dockerfile: Dcokerfile
#      context: ardupilot
#    network_mode: host

  mongo:
    image: mongo
    container_name: mongo
    network_mode: host
    volumes:
      - mongodb_data:/data/db

  predict-system:
    container_name: predict
    build:
      dockerfile: Dockerfile
      context: predict-system
    network_mode: host
    depends_on:
        - mongo

  gcs-system:
    container_name: gcs
    build:
      dockerfile: Dockerfile
      context: gcs-system
    network_mode: host
    depends_on:
      - predict-system

  web-app:
    container_name: react
    build:
      dockerfile: Dockerfile
      context: web-app
    network_mode: host
    depends_on:
      - gcs-system

volumes:
  mongodb_data: