version: '3.8'

services:
  dashboard-system:
    container_name: dashbard
    build:
      dockerfile: Dockerfile
      context: kisa-dashboard-system
    restart: always
    network_mode: host
    depends_on:
      - mongo
    environment:
      MONGO_URI_DB1: "mongodb://localhost:27017/prediction_service"
      MONGO_URI_DB2: "mongodb://localhost:27017/gcs_drone"

  gcs-system:
    container_name: gcs
    build:
      dockerfile: Dockerfile
      context: kisa-gcs-system
    restart: always
    network_mode: host
    depends_on:
      - mongo

  predict-system:
    container_name: predict
    build:
      dockerfile: Dockerfile
      context: kisa-predict-server
    restart: always
    network_mode: host
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    network_mode: host
    volumes:
      - mongodb_data:/data/db

  web-app:
    container_name: react
    build:
      dockerfile: Dockerfile
      context: ./kisa-webapp
    restart: always
    network_mode: host
    depends_on:
      - dashboard-system
      - gcs-system

volumes:
  mongodb_data: