[tool.poetry]
name = "kisa-gcs-pymavlink"
version = "0.1.0"
description = ""
authors = ["choiyun9yu <sw22tapple@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pymavlink = "^2.4.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
