# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from module import drone_pb2 as drone__pb2

class DroneStatusUpdateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDroneStatus = channel.unary_unary(
                '/kisa_gcs_system.Services.DroneStatusUpdate/UpdateDroneStatus',
                request_serializer=drone__pb2.UpdateDroneStatusPayload.SerializeToString,
                response_deserializer=drone__pb2.StatusResponse.FromString,
                )


class DroneStatusUpdateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateDroneStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DroneStatusUpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDroneStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDroneStatus,
                    request_deserializer=drone__pb2.UpdateDroneStatusPayload.FromString,
                    response_serializer=drone__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kisa_gcs_system.Services.DroneStatusUpdate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DroneStatusUpdate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateDroneStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kisa_gcs_system.Services.DroneStatusUpdate/UpdateDroneStatus',
            drone__pb2.UpdateDroneStatusPayload.SerializeToString,
            drone__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
